services:
  nginx:
    container_name: nginx-rtmp-container
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "1935:1935"
    volumes:
      - ./nginx/conf/nginx.conf.custom:/etc/nginx/nginx.conf.template

  chatbot:
    container_name: chatbot-container
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot/src/:/app
    working_dir: /usr/app
    env_file: .env

  backend:
    container_name: restreamer-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src/:/app
    working_dir: /usr/app
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=changethis
    links:
      - database
    depends_on:
      - database

  database:
    image: mongo
    container_name: database
    volumes:
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=changethis
      - MONGO_INITDB_DATABASE=banlistdb

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_URL: mongodb://root:changethis@database:27017/
#    links:
#      - database
#    depends_on:
#      - database